### ISSUE TITLE
NPM Package not working in Angular7 App

### ISSUE THREAD

**Issue by viperphase1** [KhronosGroup/glTF-Validator#110] opened 2019-02-04 22:31 UTC
I've added gltf-validator (version 2.0.0-dev.2.7) to my angular project using node. In my component ts file I'm trying to include it with

`import * as validator from 'gltf-validator'`

The app compiles with no issues but in the browser console I get this error:

> Uncaught ReferenceError: global is not defined 
at Object../node_modules/gltf-validator/gltf_validator.dart.js (gltf_validator.dart.js:1) 
at webpack_require (bootstrap:78) 
at Module../node_modules/gltf-validator/module.mjs (module.mjs:1)
at webpack_require (bootstrap:78) 
at Module../src/app/inspector/inspector.component.ts (main.js:673) 
at webpack_require (bootstrap:78) 
at Module../src/app/app.component.ts (main.js:113) 
at webpack_require (bootstrap:78) 
at Module../src/app/app.module.ts (app.component.ts:13) 
at webpack_require (bootstrap:78)

I've tried adding some polyfills but there are several variables in gltf_validator.dart.js that are undefined at runtime.

Same result when using require().
`var validator = require('gltf-validator')`

"It looks like the package may be incompatible with webpack, or some particular webpack setup." - Don McCurdy (SO)

**Comment by lexaknyazev** [comment] 2019-02-05 02:48
Thanks for the report. Could you please share your `webpack.config.js`?

**Comment by viperphase1** [comment] 2019-02-05 03:32
I don't have a custom webpack.config.js. Webpack settings are the same as they were after starting the project.

**Comment by lexaknyazev** [comment] 2019-02-05 18:15
Running `webpack` _without_ a config file produces a working build:

**index.html**
```html
<html>
    <head>
        <script src="dist/main.js"  type="application/javascript"></script>
    </head>
</html>
```
**src/index.js**
```js
import * as validator from 'gltf-validator';
const asset = '{"asset":{"version":"2.0"}}';
validator.validateString(asset).then((result) => {
    console.log(JSON.stringify(result, null, '  '));
}, (result) => {
    console.error(result);
});
```
**Building**
```
$ webpack
Hash: dd30212717555601b24f
Version: webpack 4.29.1
Time: 448ms
Built at: 2019-02-05 22:06:04
  Asset     Size  Chunks                    Chunk Names
main.js  250 KiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
[1] ./src/index.js 785 bytes {0} [built]
[3] (webpack)/buildin/global.js 472 bytes {0} [built]
[5] ./node_modules/gltf-validator sync 160 bytes {0} [built]
    + 3 hidden modules
```
**Browser console**
```
{
  "uri": "null",
  "mimeType": "model/gltf+json",
  "validatorVersion": "2.0.0-dev.2.7",
  "validatedAt": "2019-02-05T18:07:24.043Z",
...
```
---

The issue is reproducible with `webpack.config.js` looking like:
```js
module.exports = {
    target: "node"
}
```

This is expected, since `global` doesn't exist within web environment.

**Comment by lexaknyazev** [comment] 2019-02-07 15:16
@viperphase1 
Thanks again for raising this issue. Apparently, some implementation details of the npm package assume that node-specific objects are available. Tools like `webpack` or `browserify` provide shims by default, so no additional polyfills are needed.

Starting with version 6, Angular deliberately disables shims for node-specific variables. I'm going to fix this issue on our side to ensure config-free usage in the next releases.

In the meantime, you can append these lines to `src/polyfills.ts` to fix the package at runtime:
```ts
(window as any).global = window;
(window as any).process = null;
(window as any).__dirname = null;
(window as any).__filename = null;
```

**Comment by viperphase1** [comment] 2019-08-21 18:50
We would like to use gltf-validator in our project as soon as possible. Is anything being done to fix this bug?

**Comment by viperphase1** [comment] 2019-08-21 18:51
The polyfills conflict with other third party libraries we are using.

**Comment by lexaknyazev** [comment] 2019-08-21 20:02
@viperphase1 
Sorry for the delay. This issue took awhile because it was partly dependent on an upstream package and partly on the webpack itself. Both those problems have been resolved (the webpack was fixed at ` 4.32.2`).

A new validator release with a handful of new features is in progress and expected to be released within 1-2 weeks.

Given your urgency, would you prefer a bugfix release for the current validator? If so, I can backport and publish it today (or tomorrow, depending on your timezone).

**Comment by viperphase1** [comment] 2019-08-21 21:45
Yes a bugfix release would be wonderful.

**Comment by lexaknyazev** [comment] 2019-08-23 00:37
@viperphase1 
Could you please check this build with your setup?

[gltf-validator_2.0.0-dev.2.7+1.zip](https://github.com/KhronosGroup/glTF-Validator/files/3532389/gltf-validator_2.0.0-dev.2.7%2B1.zip)

**Comment by viperphase1** [comment] 2019-08-23 22:14
This is a simple component that uses gltf-validator.

`import {Component, Input, OnInit} from '@angular/core';
import * as validator from 'gltf-validator'

@Component({
  selector: 'model-summary',
  templateUrl: './model-summary.component.html',
  styleUrls: ['./model-summary.component.scss']
})
export class ModelSummaryComponent implements OnInit {
  @Input() hostedModel;
  @Input() errors;
  @Input() warnings;

  constructor() { }

  ngOnInit() {
    console.log(validator);
  }

  trim(filesize) {
    if (filesize > 1000000) {
      return Number((filesize / 1000000).toFixed(2)) + ' MB';
    } else if (filesize > 1000) {
      return Number((filesize / 1000).toFixed(2)) + ' KB';
    } else {
      return filesize + ' B';
    }
  }
}`

In the browser I'm still getting this error

> Uncaught ReferenceError: process is not defined

**Comment by lexaknyazev** [comment] 2019-08-23 23:07
@viperphase1 
If the app fails with `process is not defined` in the browser console, this means that an old webpack version is used. Also, because `angular-cli` uses its own webpack installation, it should be updated to at least `8.1`.

**Comment by viperphase1** [comment] 2019-08-23 23:14
Okay I'll try that and get back to you.

**Comment by viperphase1** [comment] 2019-08-24 00:08
Looks like it's working. Though I'm not sure what to do about this warning:

> client?719c:135 ./gltf-validator_2.0.0-dev.2.7+1/gltf_validator.dart.js
1:240-247 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Closed** 2020-01-09 16:16 UTC
Labels: bug
