### ISSUE TITLE
Warning when running within Angular

### ISSUE THREAD

**Issue by garysb** [KhronosGroup/glTF-Validator#139] opened 2020-02-28 00:42 UTC
When running within angular, we receive the following error:

./node_modules/gltf-validator/gltf_validator.dart.js 1:243-250
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by robertlong** [comment] 2020-04-13 17:57
It looks like this is caused by defining`self.require=require` and `self.exports=exports` in the node_preamble. I manually modified the minified library and was able to resolve the issue, I don't know what would have to be changed in order to fix this in tooling?

**Comment by robertlong** [comment] 2020-04-13 18:31
Looks like there's a workaround that was implemented for dart-sass: https://github.com/dart-lang/sdk/issues/25059#issuecomment-503666116

**Comment by lexaknyazev** [comment] 2020-12-02 19:57
Should be fixed in `2.0.0-dev.3.3`.

**Closed by lexaknyazev** 2020-12-02 19:57 UTC
