### ISSUE TITLE
Support resources in subdirectories in the Drag-And-Drop interface

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Validator#208] opened 2023-07-07 21:02 UTC
When dragging-and-dropping a `.gltf` file that refers to a resource (texture or buffer) that is contained in a subdirectory, _together_ with that subdirectory, into the Drag-And-Drop interface, the validator complains about missing resources.

Common viewers (Like https://gltf-viewer.donmccurdy.com/ or https://sandbox.babylonjs.com/ ) are able to resolve these resources when they are dropped together with the `.gltf` file (and they run the validator on them, and are not causing errors in this case...)

I think the validator should be able to resolve these resources as well.

As an example, the "Duck" asset, modified to put the texture and buffer into subdirectories.

[Duck with subdirectories.zip](https://github.com/KhronosGroup/glTF-Validator/files/11986055/Duck.with.subdirectories.zip)

**Comment by lexaknyazev** [comment] 2024-09-05 12:39
Duplicate of #232.

**Closed by lexaknyazev** 2024-09-05 12:39 UTC
Labels: duplicate
