### ISSUE TITLE
glTF-Validator javascript module needs require to work

### ISSUE THREAD

**Issue by kcoley** [KhronosGroup/glTF-Validator#85] opened 2018-04-18 18:18 UTC
Hello!
Is it possible to generate a version of the glTF-Validator for javascript without needing `require`?   I would like to incorporate it with a set of unit tests targetting ES5, but `require` is not an available option.
Would making it a UMD be a feasible option?

**Comment by emackey** [comment] 2018-04-18 18:48
Have you tried just directly including `gltf_validator.dart.js` from the npm distribution folder directly, instead of using `index.js`?

**Comment by lexaknyazev** [comment] 2018-04-20 17:58
`require` is used only by `index.js`. As @emackey said, it should be possible to include `gltf_validator.dart.js` directly. It fills global `exports` object with `validateBytes` and `validateString` functions with the same arguments as described in `index.js`.

Other option is to call `browserify` on the npm package like in `three-gltf-viewer`. The relevant cmd-line could be found here:
https://github.com/donmccurdy/three-gltf-viewer/blob/master/package.json

**Comment by emackey** [comment] 2018-04-25 12:55
@donmccurdy Is there something we can change about our npm package that would simplify this for users?

**Comment by donmccurdy** [comment] 2018-04-25 16:03
Not sure -  I'm using a combination of Browserify and Budo, it's possible that other bundlers handle this better. For the OP's question, a prominent link to the compiled UMD or global JS file would be enough, whether it's kept in GitHub on Unpkg. This is common enough, see the `build/*` files in the three.js repository: https://github.com/mrdoob/three.js/tree/dev/build

**Comment by lexaknyazev** [comment] 2018-04-29 13:15
What do you think about switching to ES modules? Seems to be quite straight-forward:

Current `index.js` (without comments):
```javascript
const validator = require('./gltf_validator.dart.js');
exports.validateBytes = (data, options) => validator.validateBytes(data, options);
exports.validateString = (json, options) => validator.validateString(json, options);
```
Updated `index.mjs`:
```javascript
import validator from './gltf_validator.dart.js';
export const validateBytes = (data, options) => validator.validateBytes(data, options);
export const validateString = (json, options) => validator.validateString(json, options);
```

Usage example would need to be updated from:
```javascript
const validator = require('gltf-validator');
```
to
```javascript
import * as validator from 'gltf-validator';
```

**Comment by bghgary** [comment] 2018-06-25 16:20
@lexaknyazev 
> What do you think about switching to ES modules?

I've ran into some issues with the validator mucking with the types in the global namespace which causes incompatibility with other packages. Can we can try ES modules?

**Comment by bghgary** [comment] 2018-06-25 17:10
> Incompatibilities were encountered while using it in the browser, right?

Yes.

> ES module interface will also be provided, though I'm sure it has nothing to do with the issue of global namespace corruption.

I don't know the details. @RaananW was helping me look into this and there were some issues with the global namespace.

**Comment by lexaknyazev** [comment] 2018-07-11 17:42
Global namespace issues should be resolved with the latest release. Also, it should be possible to use ES6 imports instead of `require` - [simple NodeJS example](https://github.com/KhronosGroup/glTF-Validator/pull/89#issuecomment-402099113).

/cc @bghgary @kcoley @RaananW

**Comment by bghgary** [comment] 2018-09-09 05:45
I have confirmed this is working.

**Closed by bghgary** 2018-09-09 05:45 UTC
